web/router.ex
defmodule SeoHero.Router do
  use SeoHero.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SeoHero do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/results", ResultsController, only: [:index, :delete, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", SeoHero do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron">
  <h3>Top 20 Results</h3>
  <table class="table font_8">
    <tr class="text-left">
      <th class="text-left">Rank</th>
      <th class="text-left">Domain</th>
      <th class="text-left">Link</th>
    </tr>
    <%= for result <- @collection.results do %>
      <tr title="<%= result.snippet %>">
        <td class="text-left"><%= result.rank %></td>
        <td class="text-left"><%= result.domain %></td>
        <td class="text-left"><a href="<%= result.url %>"><%= result.url %></a></td>
      </tr>
    <% end %>
  </table>
  <strong>Last updated:</strong> <%= @collection.inserted_at |> readable_date %>
  <br>
  <br>
  <p>
    <strong>URL used: </strong>
    <%= if @collection.url do %>
      <a href="<%= @collection.url %>" title="<%= @collection.url %>">Click or hover here</a>
    <%= else %>
      No url provided
    <%= end %>
  </p>
</div>

<div class="container">
  <h4>Copy this HTML to add to your own site</h4>
  <textarea rows="3" cols="50" onclick="this.focus();this.select();">
    <table class="table font_8">
      <tr class="text-center">
        <th class="text-center">Rank</th>
        <th class="text-center">Domain</th>
        <th class="text-center">Link</th>
      </tr>
      <%= for result <- @collection.results do %>
        <tr title="<%= result.snippet %>">
          <td><%= result.rank %></td>
          <td><%= result.domain %></td>
          <td><a href="<%= result.url %>"><%= result.url %></a></td>
        </tr>
      <% end %>
    </table>
    <strong>Last updated:</strong> <%= @collection.inserted_at |> readable_date %>
    <br>
    <br>
    <p>
      <strong>URL used: </strong>
      <%= if @collection.url do %>
        <a href="<%= @collection.url %>" title="<%= @collection.url %>">Click or hover here</a>
      <%= else %>
        No url provided
      <%= end %>
    </p>
  </textarea>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <%= link "Manage Results", to: results_path(@conn, :index) %>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">

  </div>
</div>